In [49]:
import pandas as pd

In [50]:
df = pd.read_csv(r'C:\Users\arace\Downloads\Datos_actividad_2.csv')

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sucursal  88 non-null     str
 1   Fecha     88 non-null     str
 2   Ingresos  88 non-null     int64
 3   Gastos    88 non-null     int64
dtypes: int64(2), str(2)
memory usage: 2.9 KB

In [52]:
df['Ganancia'] = df['Ingresos'] - df['Gastos']

df['Margen porcentual'] = (df['Ganancia'] / df['Ingresos']) * 100

print(df[['Sucursal', 'Ingresos', 'Gastos', 'Ganancia', 'Margen porcentual']])

     Sucursal  Ingresos  Gastos  Ganancia  Margen porcentual
0   Sucursal1     12000    8500      3500          29.166667
1   Sucursal2     15000   13000      2000          13.333333
2   Sucursal3     10000    7500      2500          25.000000
3   Sucursal4      9000    6000      3000          33.333333
4   Sucursal1     13000    9000      4000          30.769231
..        ...       ...     ...       ...                ...
83  Sucursal4     29000   26000      3000          10.344828
84  Sucursal1     33000   28000      5000          15.151515
85  Sucursal2     36000   34000      2000           5.555556
86  Sucursal3     31000   27000      4000          12.903226
87  Sucursal4     30000   27000      3000          10.000000

[88 rows x 5 columns]

In [53]:
df

     Sucursal      Fecha  Ingresos  Gastos  Ganancia  Margen porcentual
0   Sucursal1   1/1/2023     12000    8500      3500          29.166667
1   Sucursal2   1/1/2023     15000   13000      2000          13.333333
2   Sucursal3   1/1/2023     10000    7500      2500          25.000000
3   Sucursal4   1/1/2023      9000    6000      3000          33.333333
4   Sucursal1   1/8/2023     13000    9000      4000          30.769231
..        ...        ...       ...     ...       ...                ...
83  Sucursal4  5/21/2023     29000   26000      3000          10.344828
84  Sucursal1  5/28/2023     33000   28000      5000          15.151515
85  Sucursal2  5/28/2023     36000   34000      2000           5.555556
86  Sucursal3  5/28/2023     31000   27000      4000          12.903226
87  Sucursal4  5/28/2023     30000   27000      3000          10.000000

[88 rows x 6 columns]

In [54]:
df[['Sucursal', 'Ingresos', 'Gastos' ]].min()
df[['Sucursal', 'Ingresos', 'Gastos' ]].max()

Sucursal    Sucursal4
Ingresos        36000
Gastos          34000
dtype: object

In [55]:
df[['Ingresos', 'Gastos']].var()
df[['Ingresos', 'Gastos']].std()
df[['Ingresos', 'Gastos', 'Ganancia']].std()
sucursal = df.loc[df['Gastos'] == df['Gastos'].max()]

In [56]:
print("Desviación estándar:")
print(df[['Ingresos', 'Gastos', 'Ganancia']].std())

Desviación estándar:
Ingresos    7139.365194
Gastos      7066.495733
Ganancia    1513.123672
dtype: float64

In [57]:
df['Fecha'] = pd.to_datetime(df['Fecha'])

resumen_mensual = df.groupby(df['Fecha'].dt.month)[['Ingresos', 'Gastos']].sum()

print("Evolución mensual de ingresos y gastos:")
print(resumen_mensual)

Evolución mensual de ingresos y gastos:
       Ingresos  Gastos
Fecha
1        270000  207500
2        288000  232000
3        359320  293310
4        530000  460000
5        470500  419320

In [58]:
top5 = df.groupby('Sucursal')[['Ingresos', 'Gastos']].sum().nlargest(5, 'Ingresos')

In [60]:
resumen_mensual['top 5'] = resumen_mensual.index.isin(top5.index)
resumen_mensual

       Ingresos  Gastos  top 5
Fecha
1        270000  207500  False
2        288000  232000  False
3        359320  293310  False
4        530000  460000  False
5        470500  419320  False

In [80]:
resumen_mensual['Estrategia'] = ''

resumen_mensual.loc[
    resumen_mensual['Gastos'] < resumen_mensual['Ingresos'],
    'Estrategia'
] = 'Reducir gastos'

resumen_mensual.loc[
    resumen_mensual['Ingresos'] < resumen_mensual['Gastos'],
    'Estrategia'
] = 'Mantener gastos'

resumen_mensual

       Ingresos  Gastos  top 5      Estrategia
Fecha
1        270000  207500  False  Reducir gastos
2        288000  232000  False  Reducir gastos
3        359320  293310  False  Reducir gastos
4        530000  460000  False  Reducir gastos
5        470500  419320  False  Reducir gastos

In [81]:
resumen_mensual.to_excel('estrategias.xlsx')

In [79]:
resumen_mensual.loc[resumen_mensual['Gastos'] > resumen_mensual['Gastos'].mean(), 'Estrategia']

Fecha
4    Reducir gastos
5    Reducir gastos
Name: Estrategia, dtype: str